### ISSUE TITLE
[🐛 Bug]: 本程序不支持 Arm64 架构

### ISSUE THREAD

**Issue by ssmzhn** [chitsanfei/sekai-voice-fetch#38]
![Screenshot_2024-06-02-09-37-53-537_com.termux.jpg](https://github.com/chitsanfei/sekai-voice-fetch/assets/69438785/b11fdf5e-65c6-4776-a1ac-c75d179f969c)

如图，在 Termux proot 容器中运行的 Arch Linux 无法运行此程序。

**Comment by chitsanfei** [comment]
该错误并非发生在本项目代码中，而主要在依赖 Selenium 中：

Selenium 在代码层中限制了 ARM 架构：

https://github.com/SeleniumHQ/selenium/blob/1b827c2b297988d4856bcee666f7b593fc8dc526/py/selenium/webdriver/common/selenium_manager.py#L64-L75

根据 Selenium 的说法，由于对 ARM 平台没有官方构建的 Chrome 或者 Edge 浏览器，因而 selenium 的开发者并未构建对 ARM 平台的二进制文件，请参见： https://github.com/SeleniumHQ/selenium/issues/13542 。

由于上述原因，该问题暂不能得到解决。您可以尝试换用有图像界面的 X86 平台的 Windows/Macos 再次尝试。
